### ISSUE TITLE
undo/redo feature

### ISSUE THREAD

**Issue by 3denizotesi** [brian978/easy-sketch.js#1]
Is it possible to undo/redo drawings? If not, how can I implement this feature?

**Comment by brian978** [comment]
You can implement the features using the events that the library exposes (see the "Events triggered by the class" section in the readme file), the drawline() and clear() methods in the class.

Basically on the events you will need to register some listeners that will help you store the points that are drawn; when the user clicks on "undo" you will need to call the clear() method and redraw all the lines except the last one. For the "redo" feature you only need to draw the last line.

Please let me know if it makes sense or if you need more information.

**Comment by 3denizotesi** [comment]
Hey, thanks for response and adding this feature to next milestone. I haven't tried to implement this feature yet.

**Comment by brian978** [comment]
Added with PR #2
