### ISSUE TITLE
EasySketch is not defined

### ISSUE THREAD

**Issue by Yutenko** [brian978/easy-sketch.js#3]
Hello brian,

nice work you've done there. For me your demo is not enough to get the job done.
Is there any easysketch.min.js in the zip to use?
I have included your application.min.js and require.js from the demo. The Drawing works, but it says "EasySketch" not defined on this line:

  var sketcher = new EasySketch.Sketch("#drawing-area", options);

Can you tell me what i have to include from all of your files to start?

Many thanks in advance

**Comment by brian978** [comment]
Hello,

application.min.js contains the entire demo application (this includes EasySketch and the files in the Main module from the demo), not just the library. You need include require.js, demo/js/modules/Main/config.js, demo/js/modules/Main/app.js (in this order) and put your code in app.js.

Let me know if this helps

**Comment by Yutenko** [comment]
That actually helped. Thanks alot.
