### ISSUE TITLE
addon.attachSketchObject is not a function.

### ISSUE THREAD

**Issue by jaean123** [brian978/easy-sketch.js#4]
I tried modifying the header in index.html file in the demo folder as shown:

<head>
        <title>easy-sketch.js demo</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="js/libs/require.js"></script>
        <script src="js/modules/Main/config.js"></script>
        <script src="js/modules/Main/app.js"></script>
        
</head>

The sketching feature works but I get the error "addon.attachSketchObject is not a function."

Thanks for the help.

**Comment by brian978** [comment]
You are not importing the application correctly. You should be using it like this

        <script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="js/libs/require.js"></script>
        <script src="js/build/application.min.js"></script>
